// PDF/Print export functionality
import { DayPlan, SelectedItem } from '../lib/types';

/**
 * Generate HTML content suitable for printing/PDF export
 * @param plan - Array of DayPlan objects
 * @param city - Destination city name
 * @param vibe - Trip vibe/theme
 * @returns HTML string with formatted itinerary
 */
export function generatePDFContent(plan: DayPlan[], city: string, vibe: string): string {
  const slotLabels: Record<string, string> = {
    hotel: 'Hotel',
    breakfast: 'Breakfast',
    activity: 'Morning Activity',
    activity2: 'Afternoon Activity',
    lunch: 'Lunch',
    coffee: 'Coffee Break',
    dinner: 'Dinner',
  };

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>${city} Travel Itinerary</title>
      <style>
        body {
          font-family: 'Inter', system-ui, -apple-system, sans-serif;
          max-width: 800px;
          margin: 40px auto;
          padding: 20px;
          color: #1e293b;
        }
        h1 {
          color: #4F46E5;
          font-size: 32px;
          margin-bottom: 10px;
        }
        .subtitle {
          color: #64748b;
          margin-bottom: 40px;
          font-size: 16px;
        }
        .day {
          page-break-inside: avoid;
          margin-bottom: 40px;
        }
        .day-header {
          background: linear-gradient(135deg, #4F46E5 0%, #7C3AED 100%);
          color: white;
          padding: 15px 20px;
          border-radius: 12px;
          margin-bottom: 20px;
          font-size: 24px;
          font-weight: 600;
        }
        .slot {
          margin: 15px 0;
          padding: 15px 20px;
          border-left: 4px solid #4F46E5;
          background: #F8FAFC;
          border-radius: 8px;
        }
        .slot-label {
          font-weight: 600;
          color: #334155;
          font-size: 14px;
          text-transform: uppercase;
          letter-spacing: 0.5px;
          margin-bottom: 5px;
        }
        .slot-name {
          font-size: 18px;
          margin: 5px 0;
          color: #0f172a;
        }
        .slot-details {
          color: #64748B;
          font-size: 14px;
          margin-top: 3px;
        }
        .notes {
          background: #FEF3C7;
          border-left: 4px solid #F59E0B;
          padding: 15px 20px;
          border-radius: 8px;
          margin-top: 15px;
          font-style: italic;
          color: #78350f;
        }
        .footer {
          margin-top: 60px;
          padding-top: 20px;
          border-top: 2px solid #e2e8f0;
          text-align: center;
          color: #64748b;
          font-size: 12px;
        }
        @media print {
          body { margin: 20px; }
          .day { page-break-after: always; }
          .day:last-child { page-break-after: auto; }
        }
      </style>
    </head>
    <body>
      <h1>${city} Travel Itinerary</h1>
      <div class="subtitle">${vibe.charAt(0).toUpperCase() + vibe.slice(1)} Trip · ${plan.length} Days</div>

      ${plan.map((day, i) => `
        <div class="day">
          <div class="day-header">Day ${i + 1}</div>
          ${Object.entries(day).map(([slot, item]) => {
            if (!item || typeof item !== 'object' || !('name' in item)) return '';
            const typedItem = item as SelectedItem;
            return `
              <div class="slot">
                <div class="slot-label">${slotLabels[slot] || slot}</div>
                <div class="slot-name">${typedItem.name}</div>
                ${typedItem.area ? `<div class="slot-details">${typedItem.area}</div>` : ''}
                ${typedItem.desc ? `<div class="slot-details">${typedItem.desc}</div>` : ''}
              </div>
            `;
          }).join('')}
          ${day.notes ? `<div class="notes"><strong>Day Notes:</strong> ${day.notes}</div>` : ''}
        </div>
      `).join('')}

      <div class="footer">
        <p>Generated by Largekite Travel Planner · ${new Date().toLocaleDateString()}</p>
        <p>Powered by AI-curated recommendations</p>
      </div>
    </body>
    </html>
  `;

  return html;
}

/**
 * Export itinerary as PDF by opening print dialog
 * @param plan - Array of DayPlan objects
 * @param city - Destination city name
 * @param vibe - Trip vibe/theme
 */
export async function exportToPDF(plan: DayPlan[], city: string, vibe: string): Promise<void> {
  const html = generatePDFContent(plan, city, vibe);

  // Open in new window for printing
  const printWindow = window.open('', '', 'width=800,height=600');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();

    // Wait for content to load before printing
    printWindow.onload = () => {
      printWindow.print();
    };
  } else {
    alert('Please allow popups to export your itinerary.');
  }
}
