// PDF/Print export functionality
import { DayPlan, SelectedItem } from '../lib/types';

export type PDFTheme = 'classic' | 'modern' | 'passport' | 'minimal';

export type AccentPreset = {
  name: string;
  main: string;
  dark: string;
  light: string;
};

export const ACCENT_PRESETS: AccentPreset[] = [
  { name: 'Indigo',   main: '#4F46E5', dark: '#3730A3', light: '#EEF2FF' },
  { name: 'Rose',     main: '#E11D48', dark: '#9F1239', light: '#FFF1F2' },
  { name: 'Emerald',  main: '#059669', dark: '#065F46', light: '#ECFDF5' },
  { name: 'Amber',    main: '#D97706', dark: '#92400E', light: '#FFFBEB' },
  { name: 'Sky',      main: '#0284C7', dark: '#075985', light: '#F0F9FF' },
  { name: 'Violet',   main: '#7C3AED', dark: '#5B21B6', light: '#F5F3FF' },
];

export type PDFExportOptions = {
  theme: PDFTheme;
  accent: AccentPreset;
  includeNotes: boolean;
  includeLinks: boolean;
};

const SLOT_LABELS: Record<string, string> = {
  hotel:     'Hotel',
  breakfast: 'Breakfast',
  activity:  'Morning Activity',
  activity2: 'Afternoon Activity',
  lunch:     'Lunch',
  coffee:    'Coffee Break',
  dinner:    'Dinner',
};

const SLOT_EMOJI: Record<string, string> = {
  hotel:     '🏨',
  breakfast: '🍳',
  activity:  '🗺',
  activity2: '🎯',
  lunch:     '🍽',
  coffee:    '☕',
  dinner:    '🍷',
};

const ORDERED_SLOTS = ['hotel', 'breakfast', 'activity', 'lunch', 'activity2', 'coffee', 'dinner'];

function getSlots(day: DayPlan, includeLinks: boolean): Array<{ key: string; label: string; emoji: string; item: SelectedItem }> {
  return ORDERED_SLOTS
    .map(key => ({ key, label: SLOT_LABELS[key] ?? key, emoji: SLOT_EMOJI[key] ?? '📍', item: (day as any)[key] as SelectedItem | undefined }))
    .filter(s => s.item?.name) as Array<{ key: string; label: string; emoji: string; item: SelectedItem }>;
}

// ─── CLASSIC THEME ──────────────────────────────────────────────────────────

function classicHTML(plan: DayPlan[], city: string, vibe: string, opts: PDFExportOptions): string {
  const { main, dark } = opts.accent;
  const css = `
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Inter', system-ui, sans-serif; max-width: 800px; margin: 40px auto; padding: 30px; color: #1e293b; background: #fff; }
    .header { background: linear-gradient(135deg, ${main} 0%, ${dark} 100%); color: white; padding: 36px 40px; border-radius: 16px; margin-bottom: 40px; }
    .city { font-size: 44px; font-weight: 800; letter-spacing: -1px; }
    .subtitle { font-size: 16px; opacity: 0.85; margin-top: 8px; }
    .day { margin-bottom: 40px; page-break-inside: avoid; }
    .day-header { background: ${main}; color: white; padding: 12px 20px; border-radius: 10px; font-size: 20px; font-weight: 700; margin-bottom: 14px; }
    .slot { padding: 14px 18px; border-left: 4px solid ${main}; background: #f8fafc; border-radius: 0 8px 8px 0; margin: 8px 0; }
    .slot-label { font-size: 10px; text-transform: uppercase; letter-spacing: 1.5px; color: ${main}; font-weight: 700; margin-bottom: 4px; }
    .slot-name { font-size: 18px; font-weight: 600; color: #0f172a; }
    .slot-name a { color: ${main}; text-decoration: none; }
    .slot-area { font-size: 13px; color: #64748b; margin-top: 2px; }
    .notes { background: #fefce8; border-left: 4px solid #eab308; padding: 14px 18px; border-radius: 0 8px 8px 0; margin: 8px 0; font-size: 14px; color: #713f12; }
    .footer { margin-top: 60px; border-top: 1px solid #e2e8f0; padding-top: 20px; text-align: center; color: #94a3b8; font-size: 11px; }
    @media print { body { margin: 0; } .day { page-break-after: always; } .day:last-child { page-break-after: auto; } }
  `;
  const days = plan.map((day, i) => {
    const slots = getSlots(day, opts.includeLinks);
    return `
      <div class="day">
        <div class="day-header">Day ${i + 1}</div>
        ${slots.map(s => `
          <div class="slot">
            <div class="slot-label">${s.label}</div>
            <div class="slot-name">${opts.includeLinks && s.item.url ? `<a href="${s.item.url}" target="_blank">${s.item.name}</a>` : s.item.name}</div>
            ${s.item.area ? `<div class="slot-area">${s.item.area}</div>` : ''}
            ${s.item.desc ? `<div class="slot-area">${s.item.desc}</div>` : ''}
          </div>`).join('')}
        ${opts.includeNotes && day.notes ? `<div class="notes"><strong>Notes:</strong> ${day.notes}</div>` : ''}
      </div>`;
  }).join('');
  return base(css, `
    <div class="header">
      <div class="city">${city}</div>
      <div class="subtitle">${vibe.charAt(0).toUpperCase() + vibe.slice(1)} Trip · ${plan.length} Day${plan.length !== 1 ? 's' : ''}</div>
    </div>
    ${days}
    <div class="footer"><p>Generated by Largekite · ${new Date().toLocaleDateString()}</p></div>
  `, city);
}

// ─── MODERN THEME ───────────────────────────────────────────────────────────

function modernHTML(plan: DayPlan[], city: string, vibe: string, opts: PDFExportOptions): string {
  const { main, dark, light } = opts.accent;
  const css = `
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap');
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Inter', system-ui, sans-serif; max-width: 820px; margin: 0 auto; background: #f1f5f9; color: #1e293b; }
    .header { background: #0f172a; color: white; padding: 50px 44px 44px; }
    .header-tag { font-size: 11px; text-transform: uppercase; letter-spacing: 3px; color: ${main}; margin-bottom: 10px; }
    .city { font-size: 52px; font-weight: 900; letter-spacing: -2px; line-height: 1; }
    .vibe-pill { display: inline-block; background: ${main}; color: white; padding: 5px 14px; border-radius: 20px; font-size: 13px; font-weight: 600; margin-top: 14px; }
    .content { padding: 28px 24px; }
    .day { background: white; border-radius: 14px; margin-bottom: 20px; overflow: hidden; box-shadow: 0 1px 6px rgba(0,0,0,.07); page-break-inside: avoid; }
    .day-head { display: flex; align-items: center; padding: 18px 24px; border-bottom: 1px solid #f1f5f9; }
    .day-num { font-size: 52px; font-weight: 900; color: ${main}; line-height: 1; margin-right: 16px; }
    .day-meta { font-size: 11px; text-transform: uppercase; letter-spacing: 2px; color: #94a3b8; }
    .slots { padding: 4px 24px 16px; }
    .slot { display: flex; align-items: flex-start; padding: 12px 0; border-bottom: 1px solid #f8fafc; gap: 14px; }
    .slot:last-child { border-bottom: none; }
    .slot-icon { width: 34px; height: 34px; background: ${light}; border-radius: 8px; display: flex; align-items: center; justify-content: center; font-size: 18px; flex-shrink: 0; line-height: 1; padding-top: 2px; }
    .slot-body { flex: 1; }
    .slot-label { font-size: 10px; text-transform: uppercase; letter-spacing: 1.5px; color: #94a3b8; }
    .slot-name { font-size: 16px; font-weight: 700; color: #0f172a; margin-top: 2px; }
    .slot-name a { color: ${main}; text-decoration: none; }
    .slot-area { font-size: 12px; color: #64748b; margin-top: 1px; }
    .notes { margin: 0 24px 16px; background: #fefce8; border-radius: 8px; padding: 12px 16px; font-size: 13px; color: #713f12; }
    .footer { background: #0f172a; color: #475569; text-align: center; padding: 20px; font-size: 11px; }
    @media print { body { background: white; } .day { box-shadow: none; border: 1px solid #e2e8f0; page-break-after: always; } .day:last-child { page-break-after: auto; } }
  `;
  const days = plan.map((day, i) => {
    const slots = getSlots(day, opts.includeLinks);
    return `
      <div class="day">
        <div class="day-head">
          <div class="day-num">${String(i + 1).padStart(2, '0')}</div>
          <div class="day-meta">Day ${i + 1}</div>
        </div>
        <div class="slots">
          ${slots.map(s => `
            <div class="slot">
              <div class="slot-icon">${s.emoji}</div>
              <div class="slot-body">
                <div class="slot-label">${s.label}</div>
                <div class="slot-name">${opts.includeLinks && s.item.url ? `<a href="${s.item.url}" target="_blank">${s.item.name}</a>` : s.item.name}</div>
                ${s.item.area ? `<div class="slot-area">${s.item.area}</div>` : ''}
              </div>
            </div>`).join('')}
        </div>
        ${opts.includeNotes && day.notes ? `<div class="notes">📝 ${day.notes}</div>` : ''}
      </div>`;
  }).join('');
  return base(css, `
    <div class="header">
      <div class="header-tag">Travel Itinerary</div>
      <div class="city">${city}</div>
      <span class="vibe-pill">${vibe.charAt(0).toUpperCase() + vibe.slice(1)} · ${plan.length} Days</span>
    </div>
    <div class="content">${days}</div>
    <div class="footer">Generated by Largekite · ${new Date().toLocaleDateString()}</div>
  `, city);
}

// ─── PASSPORT THEME ─────────────────────────────────────────────────────────

function passportHTML(plan: DayPlan[], city: string, vibe: string, opts: PDFExportOptions): string {
  const { main } = opts.accent;
  const css = `
    @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700;900&display=swap');
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: Georgia, 'Times New Roman', serif; max-width: 760px; margin: 30px auto; padding: 40px; background: #fdf8f0; color: #2d1b0e; border: 16px solid #2d1b0e; }
    .header { text-align: center; padding-bottom: 28px; border-bottom: 3px double #2d1b0e; margin-bottom: 32px; }
    .passport-tag { font-family: 'Helvetica Neue', sans-serif; font-size: 10px; text-transform: uppercase; letter-spacing: 5px; color: #8b6914; margin-bottom: 12px; }
    .city { font-family: 'Playfair Display', Georgia, serif; font-size: 48px; font-weight: 900; color: ${main}; font-variant: small-caps; line-height: 1; }
    .country-bar { display: inline-block; background: ${main}; color: white; padding: 6px 22px; margin: 12px 0; font-family: 'Helvetica Neue', sans-serif; font-size: 12px; letter-spacing: 4px; text-transform: uppercase; }
    .subtitle { font-family: 'Helvetica Neue', sans-serif; font-size: 14px; color: #8b6914; margin-top: 8px; }
    .day { margin-bottom: 30px; page-break-inside: avoid; }
    .day-head { display: flex; align-items: center; margin-bottom: 14px; gap: 14px; }
    .stamp { width: 56px; height: 56px; border: 3px solid ${main}; border-radius: 50%; display: flex; flex-direction: column; align-items: center; justify-content: center; flex-shrink: 0; color: ${main}; }
    .stamp-num { font-size: 22px; font-weight: 700; line-height: 1; }
    .stamp-label { font-family: 'Helvetica Neue', sans-serif; font-size: 8px; text-transform: uppercase; letter-spacing: 1px; }
    .day-title { font-family: 'Playfair Display', Georgia, serif; font-size: 22px; font-variant: small-caps; border-bottom: 2px solid #c8a96e; padding-bottom: 8px; flex: 1; }
    .slot { padding: 10px 14px; margin: 8px 0; background: rgba(200,169,110,0.12); border: 1px solid #c8a96e; border-radius: 4px; }
    .slot-label { font-family: 'Helvetica Neue', sans-serif; font-size: 9px; text-transform: uppercase; letter-spacing: 2px; color: #8b6914; margin-bottom: 4px; }
    .slot-name { font-size: 18px; color: #2d1b0e; }
    .slot-name a { color: ${main}; text-decoration: none; }
    .slot-area { font-size: 13px; color: #6b5c47; font-style: italic; margin-top: 2px; }
    .notes { background: rgba(200,169,110,0.2); border: 1px dashed #c8a96e; padding: 12px 14px; margin: 8px 0; border-radius: 4px; font-style: italic; color: #5c4a34; font-size: 13px; }
    .footer { margin-top: 36px; text-align: center; border-top: 3px double #2d1b0e; padding-top: 18px; font-family: 'Helvetica Neue', sans-serif; font-size: 10px; color: #8b6914; letter-spacing: 3px; text-transform: uppercase; }
    @media print { body { margin: 0; border: 16px solid #2d1b0e; } .day { page-break-after: always; } .day:last-child { page-break-after: auto; } }
  `;
  const days = plan.map((day, i) => {
    const slots = getSlots(day, opts.includeLinks);
    return `
      <div class="day">
        <div class="day-head">
          <div class="stamp"><div class="stamp-num">${i + 1}</div><div class="stamp-label">Day</div></div>
          <div class="day-title">Day ${i + 1} — ${city}</div>
        </div>
        ${slots.map(s => `
          <div class="slot">
            <div class="slot-label">${s.label}</div>
            <div class="slot-name">${opts.includeLinks && s.item.url ? `<a href="${s.item.url}" target="_blank">${s.item.name}</a>` : s.item.name}</div>
            ${s.item.area ? `<div class="slot-area">${s.item.area}</div>` : ''}
          </div>`).join('')}
        ${opts.includeNotes && day.notes ? `<div class="notes">${day.notes}</div>` : ''}
      </div>`;
  }).join('');
  return base(css, `
    <div class="header">
      <div class="passport-tag">Official Travel Record</div>
      <div class="city">${city}</div>
      <div><span class="country-bar">${vibe}</span></div>
      <div class="subtitle">${plan.length}-Day Journey · ${new Date().getFullYear()}</div>
    </div>
    ${days}
    <div class="footer">Largekite Travel Planner · ${new Date().toLocaleDateString()}</div>
  `, city);
}

// ─── MINIMAL THEME ──────────────────────────────────────────────────────────

function minimalHTML(plan: DayPlan[], city: string, vibe: string, opts: PDFExportOptions): string {
  const { main } = opts.accent;
  const css = `
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700;900&display=swap');
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Inter', system-ui, sans-serif; max-width: 660px; margin: 60px auto; padding: 0 20px; color: #111; background: #fff; }
    .header { padding-bottom: 32px; border-bottom: 3px solid #111; margin-bottom: 56px; }
    .city { font-size: 56px; font-weight: 900; letter-spacing: -3px; line-height: 1; }
    .meta { font-size: 14px; color: #666; margin-top: 12px; }
    .meta-accent { color: ${main}; font-weight: 600; }
    .day { margin-bottom: 56px; page-break-inside: avoid; }
    .day-label { font-size: 10px; text-transform: uppercase; letter-spacing: 4px; color: ${main}; margin-bottom: 4px; }
    hr { border: none; border-top: 1px solid #e5e5e5; margin: 0 0 20px; }
    .slot { display: flex; align-items: baseline; gap: 24px; padding: 14px 0; border-bottom: 1px solid #f0f0f0; }
    .slot:last-of-type { border-bottom: none; }
    .slot-label { font-size: 10px; text-transform: uppercase; letter-spacing: 2px; color: #aaa; min-width: 110px; font-family: 'Courier New', Courier, monospace; flex-shrink: 0; }
    .slot-name { font-size: 17px; font-weight: 600; color: #111; }
    .slot-name a { color: ${main}; text-decoration: none; }
    .slot-area { font-size: 12px; color: #888; margin-top: 3px; }
    .notes { margin: 12px 0 20px; padding: 14px 18px; background: #fafafa; border-left: 3px solid ${main}; font-size: 13px; color: #555; font-style: italic; }
    .footer { margin-top: 80px; padding-top: 20px; border-top: 1px solid #e5e5e5; font-size: 11px; color: #bbb; }
    @media print { body { margin: 20px auto; } .day { page-break-after: always; } .day:last-child { page-break-after: auto; } }
  `;
  const days = plan.map((day, i) => {
    const slots = getSlots(day, opts.includeLinks);
    return `
      <div class="day">
        <div class="day-label">Day ${i + 1}</div>
        <hr />
        ${slots.map(s => `
          <div class="slot">
            <div class="slot-label">${s.label}</div>
            <div>
              <div class="slot-name">${opts.includeLinks && s.item.url ? `<a href="${s.item.url}" target="_blank">${s.item.name}</a>` : s.item.name}</div>
              ${s.item.area ? `<div class="slot-area">${s.item.area}</div>` : ''}
            </div>
          </div>`).join('')}
        ${opts.includeNotes && day.notes ? `<div class="notes">${day.notes}</div>` : ''}
      </div>`;
  }).join('');
  return base(css, `
    <div class="header">
      <div class="city">${city}</div>
      <div class="meta"><span class="meta-accent">${vibe.charAt(0).toUpperCase() + vibe.slice(1)}</span> · ${plan.length} Days</div>
    </div>
    ${days}
    <div class="footer">Largekite Travel Planner · ${new Date().toLocaleDateString()}</div>
  `, city);
}

// ─── SHARED WRAPPER ─────────────────────────────────────────────────────────

function base(css: string, body: string, city: string): string {
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${city} Itinerary</title><style>${css}</style></head><body>${body}</body></html>`;
}

function editableBase(css: string, body: string, city: string): string {
  const editableCSS = `
    ${css}
    /* Editable mode styles */
    [contenteditable]:hover { outline: 2px dashed #94a3b8; outline-offset: 2px; border-radius: 4px; }
    [contenteditable]:focus { outline: 2px solid #4F46E5; outline-offset: 2px; border-radius: 4px; background: #EEF2FF; }
    .edit-toolbar { position: fixed; top: 0; left: 0; right: 0; background: #1e293b; color: white; padding: 10px 20px; display: flex; align-items: center; gap: 12px; z-index: 1000; font-family: system-ui, sans-serif; box-shadow: 0 2px 8px rgba(0,0,0,0.2); }
    .edit-toolbar button { background: #4F46E5; color: white; border: none; padding: 8px 16px; border-radius: 8px; cursor: pointer; font-size: 13px; font-weight: 600; }
    .edit-toolbar button:hover { background: #4338CA; }
    .edit-toolbar button.secondary { background: transparent; border: 1px solid #475569; }
    .edit-toolbar button.secondary:hover { background: #334155; }
    .edit-toolbar .spacer { flex: 1; }
    .edit-toolbar .hint { font-size: 12px; color: #94a3b8; }
    .edit-toolbar .add-row-btn { background: #059669; }
    .edit-toolbar .add-row-btn:hover { background: #047857; }
    body { padding-top: 60px; }
    @media print { .edit-toolbar { display: none !important; } body { padding-top: 0; } [contenteditable]:hover, [contenteditable]:focus { outline: none; background: transparent; } }
  `;
  const editableScript = `
    <script>
      // Make all text content editable
      document.querySelectorAll('.slot-name, .slot-area, .notes, .city, .subtitle, .day-title, .day-label, .slot-label, .meta, .day-header, .day-meta, .slot-body').forEach(el => {
        el.setAttribute('contenteditable', 'true');
        el.setAttribute('spellcheck', 'true');
      });

      // Add a new empty day
      function addDay() {
        const days = document.querySelectorAll('.day');
        const lastDay = days[days.length - 1];
        if (!lastDay) return;
        const newDay = lastDay.cloneNode(true);
        // Update day number
        const dayNum = days.length + 1;
        newDay.querySelectorAll('.slot-name, .slot-area').forEach(el => { el.textContent = 'Click to edit'; });
        const header = newDay.querySelector('.day-header, .day-num, .stamp-num, .day-label');
        if (header) {
          if (header.classList.contains('day-num')) header.textContent = String(dayNum).padStart(2, '0');
          else if (header.classList.contains('stamp-num')) header.textContent = String(dayNum);
          else header.textContent = 'Day ' + dayNum;
        }
        const metaEl = newDay.querySelector('.day-meta, .day-title');
        if (metaEl && metaEl.classList.contains('day-meta')) metaEl.textContent = 'Day ' + dayNum;
        else if (metaEl) metaEl.textContent = 'Day ' + dayNum;
        lastDay.parentNode.insertBefore(newDay, lastDay.nextSibling);
      }

      function printPDF() {
        window.print();
      }

      function downloadHTML() {
        // Remove toolbar for download
        const toolbar = document.querySelector('.edit-toolbar');
        if (toolbar) toolbar.style.display = 'none';
        // Remove contenteditable
        document.querySelectorAll('[contenteditable]').forEach(el => el.removeAttribute('contenteditable'));
        const html = '<!DOCTYPE html>' + document.documentElement.outerHTML;
        const blob = new Blob([html], { type: 'text/html' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = document.title.replace(/[^a-zA-Z0-9]/g, '_') + '.html';
        a.click();
        URL.revokeObjectURL(url);
        // Restore
        if (toolbar) toolbar.style.display = '';
        document.querySelectorAll('.slot-name, .slot-area, .notes, .city, .subtitle, .day-title, .day-label, .slot-label, .meta, .day-header, .day-meta, .slot-body').forEach(el => {
          el.setAttribute('contenteditable', 'true');
        });
      }
    <\/script>
  `;
  const toolbar = `
    <div class="edit-toolbar">
      <strong style="font-size:14px;">Editing: ${city} Itinerary</strong>
      <span class="hint">Click any text to edit it</span>
      <span class="spacer"></span>
      <button class="add-row-btn" onclick="addDay()">+ Add Day</button>
      <button class="secondary" onclick="downloadHTML()">Download HTML</button>
      <button onclick="printPDF()">Save as PDF</button>
    </div>
  `;
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${city} Itinerary</title><style>${editableCSS}</style></head><body>${toolbar}${body}${editableScript}</body></html>`;
}

// ─── PUBLIC API ─────────────────────────────────────────────────────────────

export function generatePDFContent(plan: DayPlan[], city: string, vibe: string, opts: PDFExportOptions): string {
  switch (opts.theme) {
    case 'modern':   return modernHTML(plan, city, vibe, opts);
    case 'passport': return passportHTML(plan, city, vibe, opts);
    case 'minimal':  return minimalHTML(plan, city, vibe, opts);
    default:         return classicHTML(plan, city, vibe, opts);
  }
}

export function generateEditableContent(plan: DayPlan[], city: string, vibe: string, opts: PDFExportOptions): string {
  // Generate the same themed HTML but with editable wrapper
  let css: string;
  let body: string;

  // We need to get the css and body separately, so we reconstruct using the same logic
  // but with the editable base wrapper
  const html = generatePDFContent(plan, city, vibe, opts);
  // Extract CSS and body from the generated HTML
  const cssMatch = html.match(/<style>([\s\S]*?)<\/style>/);
  const bodyMatch = html.match(/<body>([\s\S]*?)<\/body>/);

  if (cssMatch && bodyMatch) {
    return editableBase(cssMatch[1], bodyMatch[1], city);
  }
  // Fallback: wrap entire HTML
  return editableBase('', html, city);
}

export async function exportToPDF(
  plan: DayPlan[],
  city: string,
  vibe: string,
  opts: PDFExportOptions,
): Promise<void> {
  const html = generatePDFContent(plan, city, vibe, opts);
  const printWindow = window.open('', '', 'width=900,height=700');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.onload = () => printWindow.print();
  } else {
    throw new Error('Please allow popups to export your itinerary.');
  }
}

export async function exportEditablePDF(
  plan: DayPlan[],
  city: string,
  vibe: string,
  opts: PDFExportOptions,
): Promise<void> {
  const html = generateEditableContent(plan, city, vibe, opts);
  const editWindow = window.open('', '', 'width=960,height=800');
  if (editWindow) {
    editWindow.document.write(html);
    editWindow.document.close();
  } else {
    throw new Error('Please allow popups to open the editable itinerary.');
  }
}
